{"uuid":"6782e838-2cda-422d-b7d4-f3eda6d7061f","historyId":null,"status":"broken","statusDetails":{"message":"Oops...we found an error preparing this test file:\n\n  > cypress\\e2e\\features\\tags.feature\n\n","trace":"\n\nError: Build failed with 1 error:\nerror: (3:5): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'Feature Login page will work depending on the user credentials with Tags'\n    at failureErrorWithLog (C:\\Users\\locar\\OneDrive\\Área de Trabalho\\Auditeste\\Cypress\\ChatGPT-Workshop-Auditeste\\node_modules\\esbuild\\lib\\main.js:1591:15)\n    at C:\\Users\\locar\\OneDrive\\Área de Trabalho\\Auditeste\\Cypress\\ChatGPT-Workshop-Auditeste\\node_modules\\esbuild\\lib\\main.js:1047:28\n    at runOnEndCallbacks (C:\\Users\\locar\\OneDrive\\Área de Trabalho\\Auditeste\\Cypress\\ChatGPT-Workshop-Auditeste\\node_modules\\esbuild\\lib\\main.js:1463:61)\n    at buildResponseToResult (C:\\Users\\locar\\OneDrive\\Área de Trabalho\\Auditeste\\Cypress\\ChatGPT-Workshop-Auditeste\\node_modules\\esbuild\\lib\\main.js:1045:7)\n    at C:\\Users\\locar\\OneDrive\\Área de Trabalho\\Auditeste\\Cypress\\ChatGPT-Workshop-Auditeste\\node_modules\\esbuild\\lib\\main.js:1157:14\n    at responseCallbacks.<computed> (C:\\Users\\locar\\OneDrive\\Área de Trabalho\\Auditeste\\Cypress\\ChatGPT-Workshop-Auditeste\\node_modules\\esbuild\\lib\\main.js:694:9)\n    at handleIncomingPacket (C:\\Users\\locar\\OneDrive\\Área de Trabalho\\Auditeste\\Cypress\\ChatGPT-Workshop-Auditeste\\node_modules\\esbuild\\lib\\main.js:749:9)\n    at Socket.readFromStdout (C:\\Users\\locar\\OneDrive\\Área de Trabalho\\Auditeste\\Cypress\\ChatGPT-Workshop-Auditeste\\node_modules\\esbuild\\lib\\main.js:670:7)\n    at Socket.emit (node:events:513:28)\n    at addChunk (node:internal/streams/readable:324:12)\n    at readableAddChunk (node:internal/streams/readable:297:9)\n    at Readable.push (node:internal/streams/readable:234:10)\n    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)\n\nThis occurred while Cypress was compiling and bundling your test code. This is usually caused by:\n\n- A missing file or dependency\n- A syntax error in the file or one of its dependencies\n\nFix the error in your code and re-run your tests."},"stage":"finished","attachments":[{"name":"video recording","type":"video/mp4","source":"3a68d6d7-3f2d-49ab-ae62-ba048c56e7c3-attachment.mp4"}],"parameters":[],"labels":[{"name":"suite","value":"cypress/e2e/features/tags.feature"}],"links":[],"start":1687441412200,"name":"Oops...we found an error preparing this test file: cypress/e2e/features/tags.feature","fullName":"Oops...we found an error preparing this test file: cypress/e2e/features/tags.feature","stop":1687441412200}